/**
 * Created by wsl on 2017/02/13.
 */
 import {
  StyleSheet
} from 'react-native';
import {StyleConfig} from './index';
const oPx = StyleConfig.oPx;
export default styles = StyleSheet.create({
  tableTopList:{
    height:80/oPx,
    backgroundColor:'#fff',
    flexDirection:'row',
    alignItems:'center',
  },
  tableRow:{
    flex:1,
    paddingLeft:30/oPx,
    fontSize:22/oPx,
    color:'#999',
    fontWeight:'300'
  },
  tableTop:{
    height:80/oPx,
    backgroundColor:'#e9ecf3',
    flexDirection:'row',
    alignItems:'center'
  },
  tableTopList:{
    height:80/oPx,
    backgroundColor:'#fff',
    flexDirection:'row',
    alignItems:'center',
    borderBottomWidth:StyleConfig.borderWidth,
    borderBottomColor:'#e0e0e0'
  },
  black:{
    color:'#999'
  },
  moreBottom:{
    height:80/oPx,
    justifyContent:'center',
    alignItems:'center'
  },
  dialogModal:{
    width:StyleConfig.screen_width,
    height:StyleConfig.screen_height,
    flex:1,
    position:'absolute',
    top:0,
    left:0,
  },
  modal:{
    width:StyleConfig.screen_width,
    height:StyleConfig.screen_height,
    backgroundColor:'#000',
    position:'absolute',
    top:0,
    left:0,
    zIndex:1
  },
  containerView:{
    width:520/oPx,
    height:StyleConfig.screen_height,
    position:'absolute',
    top:0,
    right:0,
    backgroundColor:'#fff',
    zIndex:10
  },
  titleView:{
    marginTop:30/oPx,
    height:68/oPx,
    justifyContent:'center',
    paddingLeft:20/oPx,
  },
  typeViewText:{
    color:'#999',
    fontSize:28/oPx
  },
  typeView:{
    paddingLeft:20/oPx,
    flexDirection:'row',
    flexWrap:'wrap',
    borderBottomWidth:StyleConfig.borderWidth,
    borderBottomColor:'#e0e0e0'
  },
  typeViewTap:{
    width:230/oPx,
    height:80/oPx,
    backgroundColor:'#e0e0e0',
    borderColor:'#e0e0e0',
    borderWidth:StyleConfig.borderWidth,
    borderRadius:5,
    justifyContent:'center',
    alignItems:'center',
    marginRight:20/oPx,
    marginBottom:20/oPx,
    overflow:'hidden'
  },
  dateView:{
    width:230/oPx,
    height:80/oPx,
    borderColor:'#e0e0e0',
    borderWidth:StyleConfig.borderWidth,
    borderRadius:5,
    justifyContent:'center',
    alignItems:'center',
    marginRight:20/oPx,
    marginBottom:20/oPx,
    overflow:'hidden'
  },
  dateViewInput:{
    width:230/oPx,
    height:80/oPx,
    color:'#333',
    fontSize:28/oPx,
    justifyContent:'center',
    alignItems:'center',
    textAlign:'center',
    fontWeight:'200'
  },
  dateText:{
    color:'#333'
  },
  choseText:{
    fontSize:28/oPx,
    fontWeight:'200',
    color:'#333'
  },
  choseTextActive:{
    color:'#eb3331'
  },
  typeViewTapActive:{
    borderWidth:StyleConfig.borderWidth,
    borderColor:'#eb3331',
    backgroundColor:'#fff',
  },
  choseIcon:{
    width:40/oPx,
    height:40/oPx,
    position:'absolute',
    right:0,
    bottom:0,
    zIndex:10,
    borderBottomRightRadius:5,
  },
  fromView:{

  },
  searchBtn:{
    height:88/oPx,
    width:520/oPx,
    position:'absolute',
    right:0,
    bottom:0,
    zIndex:10,
    backgroundColor:'#eb3331',
    justifyContent:'center',
    alignItems:'center'
  },
  searchBtnText:{
    color:'#fff',
    fontSize:28/oPx
  }

})
