import {
  StyleSheet,
} from 'react-native';
import {StyleConfig} from './index';
const oPx = StyleConfig.oPx;
export default styles = StyleSheet.create({
  container:{
    flex:1,
      backgroundColor:'#000'
  },
  scrollViewContent:{
    width:StyleConfig.screen_width,
    height:StyleConfig.content_height
  },
  imgView:{
    width:StyleConfig.screen_width,
    height:StyleConfig.content_height
  },
  ViewDialog:{
    width:StyleConfig.screen_width,
    height:StyleConfig.content_height,
    backgroundColor:'#000',
    opacity:.6,
    position:'absolute',
    left:0,
    top:0,
    zIndex:10
  },
  ViewContent:{
    width:StyleConfig.screen_width,
    height:StyleConfig.content_height,
    position:'absolute',
    left:0,
    top:0,
    zIndex:10,
    paddingLeft:60/oPx,
  },
  ViewContentFk:{
    paddingLeft:40/oPx
  },
  scrollIcon:{
    width:51/oPx,
    height:27/oPx,
    position:'absolute',
    zIndex:100,
    bottom:10,
    left:350/oPx,
  },
  toutchView:{
    width:StyleConfig.screen_width,
    height:StyleConfig.content_height,
    position:'absolute',
    left:0,
    top:StyleConfig.status_height,
    zIndex:100,
    backgroundColor:'transparent'
  },
  topView:{
    marginTop:80/oPx,
    backgroundColor:'transparent'
  },
  stepView:{
    marginTop:45/oPx,
    marginLeft:60/oPx,
    backgroundColor:'transparent',
  },
  stepViewItem:{
    alignItems:'center',
    height:100/oPx,
    backgroundColor:'transparent',
    flexDirection:'row'
  },
  centerHeight:{
  },
  lineView:{
    height:1/oPx,
    backgroundColor:'#4e4e4e',
    marginTop:20/oPx
  },
  fkLineView:{
    height:715/oPx,
    width:1/oPx,
    position:'absolute',
    top:20/oPx,
    left:124/oPx,
    zIndex:-1,
    backgroundColor:'#4e4e4e',
  },
  lineColumn:{
    height:500/oPx,
    width:1/oPx,
    position:'absolute',
    zIndex:-1,
    top:50/oPx,
    left:10/oPx,
    backgroundColor:'#4e4e4e'
  },
  pointer:{
    width:21/oPx,
    height:21/oPx,
    marginRight:30/oPx
  },
  pointerFk:{
    marginRight:10/oPx
  },
  textBig:{
    fontSize:36/oPx,
    color:'#fff',
  },
  textSmall:{
    fontSize:24/oPx,
    color:'#fff',
    lineHeight:22,
    paddingRight:60/oPx
  },
  fkLeftText:{
    width:114/oPx,
    color:'#999',
    fontSize:24/oPx,
  },
  viewFengKong:{
    marginTop:80/oPx,
  },
  viewColumn:{
    backgroundColor:'transparent',
    height:40/oPx,
    flexDirection:'row',
    alignItems:'center'
  },
  fkStepOne:{
    width:535/oPx,
    height:40/oPx,
    flexDirection:'row',
    alignItems:'center',
    paddingLeft:5/oPx
  },
  fkStepTwo:{
    width:385/oPx,
    height:40/oPx,
    flexDirection:'row',
    alignItems:'center',
    paddingLeft:5/oPx
  },
  fkStepThree:{
    width:255/oPx,
    height:40/oPx,
    flexDirection:'row',
    alignItems:'center',
    paddingLeft:5/oPx
  },
  fkStepFour:{
    width:405/oPx,
    height:40/oPx,
    flexDirection:'row',
    alignItems:'center',
    paddingLeft:5/oPx
  },
  fkStepOneLine:{
    width:291/oPx,
    height:53/oPx,
    alignSelf:'flex-end',
    marginRight:98/oPx
  },
  fkStepTwoLine:{
    width:61/oPx,
    height:52/oPx,
    marginLeft:186/oPx
  },
  fkDownBg:{
    width:40/oPx,
    height:120/oPx,
    alignItems:'center',
    justifyContent:'center',
    backgroundColor:'rgba(255,255,255, 0.2)',
    marginRight:20/oPx
  },
  fkDownBgLast:{
    marginRight:0,
    marginLeft:50/oPx
  },
  fkDownBgText:{
    fontSize:24/oPx,
    color:'#fff',
    textAlign:'center'
  },
  stepViewText:{
    fontSize:24/oPx,
    color:'#fff',
    flex:1,
  },
  stepViewTextNo:{
    fontSize:24/oPx,
    color:'#fff',
  },
  fkDownView:{
    height:175/oPx,
  },
  fkDownStepView:{
    flexDirection:'row',
    width:330/oPx,
    alignSelf:'flex-end',
    marginRight:80/oPx,
  },
  fkDownThreeView:{
    width:120/oPx,
    alignSelf:'flex-start',
    marginRight:1,
    marginLeft:167/oPx
  },
  fkLeftTextView:{

  }

})
